spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: phegonbank
  datasource:
    url: ${LOCAL_DB_URL}
    username: ${LOCAL_DB_USERNAME}
    password: ${LOCAL_DB_PASSWORD}

server:
  port: 8080