spring:
  config:
    import: optional:file:.env[.properties]

  application:
    name: phegonbank

  datasource:
    url: ${LOCAL_DB_URL}
    username: ${LOCAL_DB_USERNAME}
    password: ${LOCAL_DB_PASSWORD}

  # Configuração do JPA/Hibernate
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true  # opcional — exibe as queries no console

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USER}
    password: ${MAIL_PASS}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

server:
  port: 8080

jwt:
  secret:
    string: ${JWT_SECRET}
  expiration:
    time: ${JWT_EXPIRATION_TIME}

password:
  reset:
    link: http://localhost:3000/reset-password?code=