spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: phegonbank
  datasource:
    url: ${LOCAL_DB_URL}
    username: ${LOCAL_DB_USERNAME}
    password: ${LOCAL_DB_PASSWORD}
  mail:
    username: ${MAIL_USER}
    password: ${MAIL_PASSWORD}
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enabled: true
          required: true

server:
  port: 8080

jwt:
  secret:
    string: ${JWT_SECRET}
  expiration:
    time: ${JWT_EXPIRATION_TIME}

#Mail Configuration
